module.exports = {
  positionPoints: [40, 35, 30, 27, 24, 22, 20, 18, 16, 14, 12, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  polePositionPoints: 1,
  fastestLapPoints: 1,
  divisions: {
    Elite: [
      'Alberto Gravili',
      'Charlie Bebb',
      'Daryl Norkett',
      'Dominic Roberts',
      'James T Armstrong',
      'Jonathan Hitchen',
      'NL Print',
      'Paul Busby',
      'Stuart Bickley',
      'Tim Darracott',
    ],
    Pro: [
      'Ben Cullen2',
      'Chris Eddisford',
      'Chris Hitchen',
      'Damian Gee',
      'Gary Bacon',
      'Lee Green',
      'Rob Sandford',
      'Sean Joe',
      'Si Anthony',
      'Stephen A Masters',
    ],
    Am: [
      'Anthony Franklin',
      'Ash Wheeler',
      'Bradley Hulse',
      'Carrick Stonehouse',
      'Colin Wynn',
      'Daniel Smith33',
      'David Lowerson',
      'Gary Trubey',
      'Murray Luker2',
      'Neal Smith3',
      'Rob J Armstrong',
      'Steve P Hughes',
      'Thom Carroll',
      'Tom F Farrell',
      'Trevor M Davis',
    ],
    Rookie: [
      'Austin William Campbell',
      'Carl Sharkey',
      'Chris Chadderton',
      'Damian R Lobbett',
      'Daniel W Taylor',
      'Danny Gosling',
      'Darren Wyllie',
      'Dave A Stringfellow',
      'David Contos',
      'Gianni Pirone',
      'Harry Fox',
      'Jacob Hyde2',
      'Jake Cherrill JC',
      'John Watt2',
      'Jon Williams',
      'Joshua Pratt',
      'Kiefer McKenna',
      'Mark Jennings2',
      'Mark Johnson',
      'Matt A Cox',
      'Matthew Struthers2',
      'Morgan Driscoll',
      'Nathan P Willoughby',
      'Oli Pimley',
      'Owen Blythe',
      'Paul Stout',
      'Peter Cox',
      'Richard Jones15',
      'Ryan James Ward',
      'Samuel Hooper',
      'Shane Abbott',
      'Simon Bamber',
      'Steve Smith12',
      'Stuart Brown',
      'Thijn van den Wittenboer',
      'Tom Noble',
      'Tom Tennant',
      'Xander Hill',
    ],
  }
};
